CREATE SCHEMA learning_curve_schema ;


CREATE TABLE   learning_curve_schema . users  (
 USER_ID  INT NOT NULL  AUTO_INCREMENT,
 USER_NAME  VARCHAR(45) NOT NULL,
 PASSWORD  VARCHAR(45) NOT NULL,
 AGE_GRP_RANGE varchar(45) DEFAULT NULL ,
 PRIMARY KEY ( USER_ID ));

CREATE TABLE  learning_curve_schema . scores  (
 USER_ID  INT NOT NULL ,
 SCORE_ID  INT NOT NULL AUTO_INCREMENT ,
 GAME_ID  INT NOT NULL,
 SCORE  INT NOT NULL,
 PRIMARY KEY (SCORE_ID) ,
 FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
 FOREIGN KEY (GAME_ID) REFERENCES games(GAME_ID)
 );

CREATE TABLE `mcq_game` (
  `QUESTION_ID` int NOT NULL AUTO_INCREMENT,
  `GAME_ID` int NOT NULL,
  `QUESTION` varchar(45) NOT NULL,
  `OPTION_1` varchar(45) NOT NULL,
  `OPTION_2` varchar(45) NOT NULL,
  `OPTION_3` varchar(45) NOT NULL,
  `OPTION_4` varchar(45) NOT NULL,
  `ANSWER` int NOT NULL,
  PRIMARY KEY (`QUESTION_ID`),
  KEY `GAME_ID` (`GAME_ID`),
  CONSTRAINT `mcq_game_ibfk_1` FOREIGN KEY (`GAME_ID`) REFERENCES `games` (`GAME_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


 CREATE TABLE   learning_curve_schema . mtfGame  (
   QUESTION_ID  INT NOT NULL AUTO_INCREMENT,
   GAME_ID  INT NOT NULL,
   QUESTION  VARCHAR(45) NOT NULL,
   OPTIONS  VARCHAR(45) NOT NULL,
   ANSWERS  INT NOT NULL,
   PRIMARY KEY (QUESTION_ID),
   FOREIGN KEY ( GAME_ID ) REFERENCES games(GAME_ID)
  ) ;

